### ISSUE TITLE
Is it possible to specify an audience with an OAuth 2.0 authorization request?

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-react-native#533]
**Describe the bug**

I'm trying to get this blueprint working with Auth0. One thing I've learned is Auth0 requires an `audience` parameter with the initial authorization request in order to receive the access token as a JWT. Is it possible to do that?

Related: does the `oktaClientId` in the following file cause special behavior? 

https://github.com/jhipster/generator-jhipster-react-native/blob/main/generators/app/templates/app/config/app-config.js.ejs

If so, maybe we should rename it to `nativeClientId`?

**JHipster app's `.yo-rc.json`**

https://github.com/oktadev/auth0-full-stack-java-example/blob/main/.yo-rc.json

**Entity JDL or JSON files**

**Versions (please complete the following information):**

- JHipster React Native Version: latest
- `jhipster info` output:

**Comment by ruddell** [comment]
For audience, maybe check https://github.com/jhipster/generator-jhipster-react-native/blob/5d09bc6ceb6d798bc901ac402c37532546b5d621/generators/app/templates/app/modules/login/login.utils.ts.ejs#L19-L27

Renamed to nativeClientId. It overrides the client ID from the backend, which doesn't work for Okta since it needs to be the native client ID.

Planning to release an update fixing images and OAuth2 as soon as CI passes on the PR

**Comment by mraible** [comment]
@ruddell Adding `audience` to the code block above works! Maybe we should specify a default?

```js
const authenticationOptions = {
  response_type: 'code',
  code_challenge: codeChallenge,
  code_challenge_method: 'S256',
  scope: ['openid', 'profile', 'email', 'address', 'phone', 'offline_access'].join(' '),
  state,
  client_id: clientId,
  redirect_uri: redirectUri,
  audience: 'api://default',
};
```

^^ works for Okta and Keycloak.
